version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
    
jobs:
  install-deps:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - package.json
            - package-lock.json
            - index.html
            - src
            - public
            - .elasticbeanstalk
            - server.cjs

  build:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build the project
          command: npm run build  
      - persist_to_workspace:
          root: .
          paths:
            - dist  

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: . 
      - run:
          name: Install Python and pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
      - run:
          name: Install AWS EB CLI
          command: |
            pip3 install --upgrade pip
            pip3 install awsebcli --upgrade --user
            export PATH=$HOME/.local/bin:$PATH
      - run:
          name: list files
          command: |
            ls -la
            cat .elasticbeanstalk/config.yml || echo "No config file found"
      - run:
          name: Deploy to AWS Elastic Beanstalk
          command: |
            export PATH=$HOME/.local/bin:$PATH
            eb deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install-deps
      - build:
          requires:
            - install-deps
      - deploy:
          requires:
            - build

